-- Rent schedule: every Active contract gets one payment row per month, from
-- start_date up to (not including) end_date. payment_date is the DUE date of
-- that installment; paid_at records when it was actually paid.
--
-- Status lifecycle of an installment:
--   Scheduled  due more than 7 days from today (not payable yet)
--   Pending    due within the next 7 days, or today (payable)
--   Late       due date has passed and it is still unpaid (payable)
--   Paid       paid (set by the Wompi webhook, or by the owner for manual payments)
--   Cancelled  the contract ended before this installment came due

-- 1. Schema --------------------------------------------------------------

alter table public.payment drop constraint if exists payment_status_check;
alter table public.payment add constraint payment_status_check
    check (status in ('Scheduled', 'Pending', 'Paid', 'Late', 'Cancelled'));

-- Unpaid installments have no payment method yet.
alter table public.payment alter column payment_method drop not null;

alter table public.payment add column if not exists paid_at timestamptz;
update public.payment
set paid_at = payment_date::timestamptz
where status = 'Paid' and paid_at is null;

-- The old rule allowed a single Pending/Late payment per contract, because
-- payments were created one at a time at checkout. With a schedule, a tenant
-- can legitimately owe more than one month; what must stay unique is one open
-- installment per contract per due date.
drop index if exists public.payment_one_pending_per_contract;
create unique index if not exists payment_one_open_installment_per_date
    on public.payment (contract_id, payment_date)
    where status in ('Scheduled', 'Pending', 'Late');

-- Tenants must not insert payment rows themselves (they could insert one
-- already marked Paid). Installments are generated by the database, and Paid
-- is only ever set server-side by the Wompi webhook.
drop policy if exists "Tenants can record payments on their contracts" on public.payment;

-- 2. Helpers -------------------------------------------------------------

-- "Today" in El Salvador, not UTC, so an installment doesn't turn Late at
-- 6pm local time the day it's due.
create or replace function public.sv_today()
returns date
language sql
stable
as $$
    select (now() at time zone 'America/El_Salvador')::date
$$;

create or replace function public.installment_status_for(p_due date)
returns text
language sql
stable
as $$
    select case
        when p_due < public.sv_today() then 'Late'
        when p_due <= public.sv_today() + 7 then 'Pending'
        else 'Scheduled'
    end
$$;

-- 3. Schedule generation -------------------------------------------------

-- Creates the missing monthly installments for one Active contract. Safe to
-- call repeatedly: a month that already has a non-cancelled payment row is
-- skipped, so re-running never duplicates and never touches paid months.
create or replace function public.generate_rent_schedule(p_contract_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    c record;
    v_due date;
    v_n integer := 0;
    v_created integer := 0;
begin
    select contract_id, status, start_date, end_date, monthly_rent
    into c
    from contract
    where contract_id = p_contract_id;

    if not found
        or c.status <> 'Active'
        or c.start_date is null
        or c.end_date is null
        or c.end_date <= c.start_date then
        return 0;
    end if;

    loop
        -- start_date + n months (not repeated +1 month), so a lease starting
        -- on the 31st doesn't drift to the 28th after February.
        v_due := (c.start_date + make_interval(months => v_n))::date;
        exit when v_due >= c.end_date or v_n >= 120;

        if not exists (
            select 1
            from payment p
            where p.contract_id = c.contract_id
              and p.status <> 'Cancelled'
              and date_trunc('month', p.payment_date) = date_trunc('month', v_due)
        ) then
            insert into payment (contract_id, payment_date, amount, status)
            values (c.contract_id, v_due, c.monthly_rent, installment_status_for(v_due));
            v_created := v_created + 1;
        end if;

        v_n := v_n + 1;
    end loop;

    return v_created;
end;
$$;

revoke all on function public.generate_rent_schedule(bigint) from public, anon, authenticated;

create or replace function public.contract_rent_schedule_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.status = 'Active' and (
        tg_op = 'INSERT'
        or old.status is distinct from 'Active'
        or old.start_date is distinct from new.start_date
        or old.end_date is distinct from new.end_date
    ) then
        perform generate_rent_schedule(new.contract_id);
    elsif tg_op = 'UPDATE'
        and old.status = 'Active'
        and new.status in ('Cancelled', 'Expired') then
        -- Months that haven't come due yet are no longer owed. Anything
        -- already Late stays owed.
        update payment
        set status = 'Cancelled'
        where contract_id = new.contract_id
          and status in ('Scheduled', 'Pending')
          and payment_date > sv_today();
    end if;

    return null;
end;
$$;

drop trigger if exists contract_rent_schedule on public.contract;
create trigger contract_rent_schedule
    after insert or update of status, start_date, end_date on public.contract
    for each row
    execute function public.contract_rent_schedule_trigger();

-- 4. Status refresh ------------------------------------------------------

-- Moves installments forward as their due dates approach and pass
-- (Scheduled -> Pending -> Late). Idempotent; runs daily via pg_cron and is
-- also called by the app when a Payments screen loads, so the page is never
-- a day behind.
create or replace function public.refresh_payment_statuses()
returns void
language sql
security definer
set search_path = public
as $$
    update payment p
    set status = installment_status_for(p.payment_date)
    from contract c
    where c.contract_id = p.contract_id
      and c.status = 'Active'
      and p.status in ('Scheduled', 'Pending')
      and installment_status_for(p.payment_date) <> p.status;
$$;

revoke all on function public.refresh_payment_statuses() from public, anon;
grant execute on function public.refresh_payment_statuses() to authenticated;

-- 5. Payment-received notification uses the real paid date ----------------

create or replace function public.claim_and_notify_payment(p_payment_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_contract_id bigint;
    v_amount numeric;
    v_paid_on date;
begin
    -- Atomically claim the right to notify for this payment: only one caller can ever
    -- flip notified_at from null, regardless of how many times this function is invoked
    -- (retries, concurrent webhook deliveries, etc.) for the same payment_id.
    update payment
    set notified_at = now()
    where payment_id = p_payment_id
      and status = 'Paid'
      and notified_at is null
    returning contract_id, amount, coalesce(paid_at, now())::date
    into v_contract_id, v_amount, v_paid_on;

    if not found then
        return false;
    end if;

    -- Same transaction as the claim above: if this insert fails for any reason, the
    -- whole transaction (claim included) rolls back, so notified_at stays null and a
    -- future call can retry -- the claim and the notification succeed or fail together.
    insert into notifications (recipient_dui, sender_dui, process, title, description, contract_id)
    select
        b.owner_id,
        c.tenant_dui,
        'Payments',
        'Payment received: ' || coalesce(b.property_name, 'your property'),
        '$' || to_char(v_amount, 'FM999,999,990.00') || ' was paid on ' || v_paid_on::text || '.',
        v_contract_id
    from contract c
    join add_business b on b.property_id = c.property_id
    where c.contract_id = v_contract_id;

    return true;
end;
$$;

-- 6. Backfill existing Active contracts, then bring statuses up to date ---

select public.generate_rent_schedule(contract_id)
from public.contract
where status = 'Active';

-- Old checkout-created rows that were Pending with a past date become Late.
update public.payment p
set status = 'Late'
from public.contract c
where c.contract_id = p.contract_id
  and c.status = 'Active'
  and p.status = 'Pending'
  and p.payment_date < public.sv_today();

select public.refresh_payment_statuses();
