import { formatDueDate } from './rentSchedule'

const NAVY = [15, 42, 82]
const MUTED = [110, 120, 138]
const TEXT = [26, 31, 43]
const GREEN = [26, 138, 74]

function money(value) {
    return `$${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function paidOn(payment) {
    if (!payment.paid_at) return '—'
    return new Date(payment.paid_at).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
        timeZone: 'America/El_Salvador',
    })
}

export function receiptNumber(payment) {
    return `NS-${String(payment.payment_id).padStart(6, '0')}`
}

function fullName(person) {
    return [person?.first_name, person?.last_name].filter(Boolean).join(' ') || '—'
}

// Builds and downloads a one-page PDF receipt for a Paid installment.
// jsPDF is loaded on demand so it isn't part of the main bundle.
export async function downloadReceiptPdf({ payment, contract, tenant }) {
    const { jsPDF } = await import('jspdf')
    const doc = new jsPDF({ unit: 'pt', format: 'letter' })
    const pageWidth = doc.internal.pageSize.getWidth()
    const left = 56
    const right = pageWidth - 56
    const property = contract.add_business || {}

    // Header band
    doc.setFillColor(...NAVY)
    doc.rect(0, 0, pageWidth, 96, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.text('NextSpace', left, 52)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.text('Rent payment receipt', left, 72)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text(receiptNumber(payment), right, 52, { align: 'right' })
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Issued ${paidOn(payment)}`, right, 72, { align: 'right' })

    // Amount block
    let y = 150
    doc.setTextColor(...MUTED)
    doc.setFontSize(10)
    doc.text('AMOUNT PAID', left, y)
    doc.setTextColor(...TEXT)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(30)
    doc.text(money(payment.amount), left, y + 34)
    doc.setFontSize(11)
    doc.setTextColor(...GREEN)
    doc.text('PAID', right, y + 30, { align: 'right' })

    // Detail rows
    const rows = [
        ['Rent period', formatDueDate(payment.payment_date, { month: 'long', year: 'numeric' })],
        ['Due date', formatDueDate(payment.payment_date, { month: 'long', day: 'numeric', year: 'numeric' })],
        ['Paid on', paidOn(payment)],
        ['Payment method', payment.payment_method || '—'],
        ['Transaction ID', payment.wompi_transaction_id || '—'],
        ['Property', property.property_name || '—'],
        ['Contract', `#${contract.contract_id}  (${formatDueDate(contract.start_date)} – ${formatDueDate(contract.end_date)})`],
        ['Tenant', `${fullName(tenant)}${tenant?.dui ? `  ·  DUI ${tenant.dui}` : ''}`],
        ['Property owner', fullName(property.users)],
    ]

    y += 80
    doc.setDrawColor(229, 234, 243)
    doc.setLineWidth(1)
    doc.line(left, y - 22, right, y - 22)

    for (const [label, value] of rows) {
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        doc.setTextColor(...MUTED)
        doc.text(label, left, y)
        doc.setTextColor(...TEXT)
        doc.setFontSize(11)
        doc.text(String(value), left + 150, y, { maxWidth: right - left - 150 })
        y += 28
    }

    doc.line(left, y - 8, right, y - 8)

    doc.setFontSize(9)
    doc.setTextColor(...MUTED)
    doc.text(
        'This receipt was generated by NextSpace from the payment confirmed through Wompi. ' +
            'Keep it as proof of payment for this rent period.',
        left,
        y + 20,
        { maxWidth: right - left }
    )

    doc.save(`NextSpace-receipt-${receiptNumber(payment)}.pdf`)
}
